#!/usr/bin/env python3
"""
Visualize bound splitting tree from JSONL logs.

Usage:
    python visualize_tree.py <jsonl_log_file> [--output <output_prefix>]

The script reads a JSONL log file generated by bound_splitting and produces:
1. ASCII tree visualization
2. DOT file (always)
3. SVG tree diagram (if graphviz is available)
4. Statistics summary
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

# python visualize_tree.py logs/verification_tree_*.jsonl


# ---------------------------------------------------------------------------
# JSONL loader  (one JSON object per line — no full array held in memory)
# ---------------------------------------------------------------------------

def load_jsonl(path: Path) -> List[Dict]:
    """Read a JSONL file and return a list of node dicts."""
    nodes = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                nodes.append(json.loads(line))
    return nodes


# ---------------------------------------------------------------------------
# Tree node
# ---------------------------------------------------------------------------

class TreeNode:
    def __init__(self, node_dict: Dict):
        self.node_id          = node_dict.get("node_id")
        self.parent_id        = node_dict.get("parent_id")
        self.depth            = node_dict.get("depth", 0)
        self.level            = node_dict.get("level", 0)
        self.throughput_lb    = node_dict.get("throughput_lb", 0.0)
        self.throughput_ub    = node_dict.get("throughput_ub", 0.0)
        self.throughput_all_lb = node_dict.get("throughput_all_lb", [])
        self.throughput_all_ub = node_dict.get("throughput_all_ub", [])
        self.download_time_lb  = node_dict.get("download_time_lb", [])
        self.download_time_ub  = node_dict.get("download_time_ub", [])
        self.last_br_lb        = node_dict.get("last_br_lb", 0.0)
        self.last_br_ub        = node_dict.get("last_br_ub", 0.0)
        self.current_br_lb     = node_dict.get("current_br_lb", 0.0)
        self.current_br_ub     = node_dict.get("current_br_ub", 0.0)
        self.buffer_lb         = node_dict.get("buffer_lb", 0.0)
        self.buffer_ub         = node_dict.get("buffer_ub", 0.0)
        self.status            = node_dict.get("status")
        self.action            = node_dict.get("action")
        self.children: List["TreeNode"] = []

    def add_child(self, child: "TreeNode"):
        self.children.append(child)

    def __repr__(self):
        return (f"Node({self.node_id}, depth={self.depth}, status={self.status}, "
                f"throughput=[{self.throughput_lb:.4f}, {self.throughput_ub:.4f}])")


# ---------------------------------------------------------------------------
# Tree
# ---------------------------------------------------------------------------

class BoundSplittingTree:
    """
    Manages and visualises the bound splitting tree.

    The JSONL file already contains only root SPLIT nodes and SAFE leaves —
    no filtering is needed here.
    """

    def __init__(self, node_dicts: List[Dict]):
        self.nodes_by_id: Dict[int, TreeNode] = {}
        self.roots: List[TreeNode] = []
        self.root: Optional[TreeNode] = None

        for d in node_dicts:
            node = TreeNode(d)
            self.nodes_by_id[node.node_id] = node

        for node in self.nodes_by_id.values():
            if node.parent_id is None:
                self.roots.append(node)
                if self.root is None:
                    self.root = node
            else:
                parent = self.nodes_by_id.get(node.parent_id)
                if parent:
                    parent.add_child(node)

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    def get_statistics(self) -> Dict:
        stats = {
            "total_nodes":   len(self.nodes_by_id),
            "safe_regions":  0,
            "root_nodes":    0,
            "safe_actions":  {},
        }
        for node in self.nodes_by_id.values():
            if node.status == "SAFE":
                stats["safe_regions"] += 1
                stats["safe_actions"].setdefault(node.action, 0)
                stats["safe_actions"][node.action] += 1
            elif node.parent_id is None:
                stats["root_nodes"] += 1
        return stats

    # ------------------------------------------------------------------
    # ASCII output
    # ------------------------------------------------------------------

    def print_hierarchical_tree(self) -> str:
        """
        Print a two-level view per verification round:
          🟡 root SPLIT node
          🟢 SAFE leaf nodes attached to it
        """
        output = ""

        roots_by_level: Dict[int, List[TreeNode]] = {}
        safe_by_root:   Dict[int, List[TreeNode]] = {}

        for node in self.nodes_by_id.values():
            if node.parent_id is None:
                roots_by_level.setdefault(node.level, []).append(node)
                safe_by_root.setdefault(node.node_id, [])
            elif node.status == "SAFE":
                safe_by_root.setdefault(node.parent_id, []).append(node)

        for level in sorted(roots_by_level.keys()):
            output += f"\n{'='*70}\n"
            output += f"VERIFICATION ROUND {level}\n"
            output += f"{'='*70}\n\n"

            for root in sorted(roots_by_level[level], key=lambda n: n.node_id):
                output += f"🟡 [Root Node {root.node_id}] — Split root\n"
                output += f"   Throughput: [{root.throughput_lb:.4f}, {root.throughput_ub:.4f}]\n\n"

                safe_children = sorted(
                    safe_by_root.get(root.node_id, []), key=lambda n: n.node_id
                )

                if not safe_children:
                    output += "   (no SAFE regions certified)\n\n"
                    continue

                output += f"   SAFE regions ({len(safe_children)}):\n"
                for i, node in enumerate(safe_children):
                    connector = "└──" if i == len(safe_children) - 1 else "├──"
                    output += f"   {connector} 🟢 [Node {node.node_id}] Depth {node.depth}\n"
                    output += f"          Throughput : [{node.throughput_lb:.4f}, {node.throughput_ub:.4f}]\n"

                    if node.throughput_all_lb and node.throughput_all_ub:
                        slots = " | ".join(
                            f"[{node.throughput_all_lb[i]:.3f}, {node.throughput_all_ub[i]:.3f}]"
                            for i in range(8)
                        )
                        output += f"          All slots  : {slots}\n"

                    if node.download_time_lb and node.download_time_ub:
                        slots = " | ".join(
                            f"[{node.download_time_lb[i]:.3f}, {node.download_time_ub[i]:.3f}]"
                            for i in range(8)
                        )
                        output += f"          Dl. time   : {slots}\n"

                    output += (
                        f"          Last BR    : [{node.last_br_lb:.4f}, {node.last_br_ub:.4f}]  |  "
                        f"Buffer: [{node.buffer_lb:.4f}, {node.buffer_ub:.4f}]\n"
                        f"          ✓ Action {node.action} dominates\n\n"
                    )

        return output

    # ------------------------------------------------------------------
    # DOT / SVG output
    # ------------------------------------------------------------------

    def to_dot_format(self) -> str:
        dot_lines = [
            "digraph BoundSplittingTree {",
            "  rankdir=TB;",
            "  node [shape=box, style=rounded];",
            "  compound=true;",
        ]

        nodes_by_level: Dict[int, List[TreeNode]] = {}
        for node in self.nodes_by_id.values():
            nodes_by_level.setdefault(node.level, []).append(node)

        for level in sorted(nodes_by_level.keys()):
            dot_lines.append(f'  subgraph cluster_level_{level} {{')
            dot_lines.append(f'    label="Verification Level {level}";')
            dot_lines.append(f'    style=dotted;')

            for node in nodes_by_level[level]:
                tput_str = f"Throughput: [{node.throughput_lb:.4f}, {node.throughput_ub:.4f}]"

                if node.throughput_all_lb and node.throughput_all_ub:
                    tput_str += "\\nAll Throughput:\\n" + "".join(
                        f"  Slot {i}: [{node.throughput_all_lb[i]:.3f}, {node.throughput_all_ub[i]:.3f}]\\n"
                        for i in range(8)
                    )

                dt_str = "\\nDownload Time:\\n"
                if node.download_time_lb and node.download_time_ub:
                    dt_str += "".join(
                        f"  Slot {i}: [{node.download_time_lb[i]:.3f}, {node.download_time_ub[i]:.3f}]\\n"
                        for i in range(8)
                    )

                br_buffer = (
                    f"\\nLast BR: [{node.last_br_lb:.4f}, {node.last_br_ub:.4f}]"
                    f"\\nBuffer: [{node.buffer_lb:.4f}, {node.buffer_ub:.4f}]"
                    f"\\nVer. Level: {node.level} | Node ID: {node.node_id}"
                )

                label = tput_str + dt_str + br_buffer
                if node.action is not None:
                    label += f"\\n✓ Action: {node.action}"

                color = "lightgreen" if node.status == "SAFE" else "lightyellow"
                dot_lines.append(
                    f'    node_{node.node_id} [label="{label}", '
                    f'fillcolor={color}, style="rounded,filled"];'
                )

            dot_lines.append("  }")

        for node in self.nodes_by_id.values():
            for child in node.children:
                dot_lines.append(f"  node_{node.node_id} -> node_{child.node_id};")

        dot_lines.append("}")
        return "\n".join(dot_lines)

    def save_dot_file(self, output_path: Path):
        output_path.write_text(self.to_dot_format())
        print(f"Saved DOT file to {output_path}")

    def generate_svg(self, output_path: Path):
        try:
            import graphviz
        except ImportError:
            print("Warning: graphviz not installed. Cannot generate SVG.")
            print("Install with: pip install graphviz")
            return

        output_stem = str(output_path).replace(".dot", "").replace(".svg", "")
        try:
            graphviz.Source(self.to_dot_format()).render(output_stem, format="svg", cleanup=True)
            print(f"Saved SVG to {output_stem}.svg")
        except Exception as e:
            print(f"Warning: Could not generate SVG: {e}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Visualize bound splitting tree from JSONL logs"
    )
    parser.add_argument("jsonl_log", type=str, help="Path to JSONL log file")
    parser.add_argument("--output", type=str, default=None,
                        help="Output prefix for generated files (without extension)")
    parser.add_argument("--no-ascii", action="store_true", help="Skip ASCII tree output")
    parser.add_argument("--dot-only", action="store_true", help="Only generate DOT file (not SVG)")
    args = parser.parse_args()

    jsonl_file = Path(args.jsonl_log)
    if not jsonl_file.exists():
        print(f"Error: File not found: {jsonl_file}")
        sys.exit(1)

    node_dicts = load_jsonl(jsonl_file)
    tree = BoundSplittingTree(node_dicts)

    print("=" * 70)
    print("BOUND SPLITTING TREE ANALYSIS")
    print("=" * 70)
    stats = tree.get_statistics()
    print(f"Total Nodes Shown  : {stats['total_nodes']}  (root + SAFE only)")
    print(f"Safe Regions       : {stats['safe_regions']}")
    print(f"Root (Split) Nodes : {stats['root_nodes']}")

    if stats["safe_actions"]:
        print("\nSafe Actions Found:")
        for action, count in sorted(stats["safe_actions"].items()):
            print(f"  Action {action}: {count} region(s)")
    print("=" * 70)
    print()

    if not args.no_ascii:
        print("TREE VISUALIZATION (ASCII):")
        print("-" * 70)
        print(tree.print_hierarchical_tree())
        print("-" * 70)
        print()

    output_base = Path(args.output) if args.output else jsonl_file.parent / jsonl_file.stem

    dot_path = Path(str(output_base) + ".dot")
    tree.save_dot_file(dot_path)

    if not args.dot_only:
        tree.generate_svg(Path(str(output_base) + ".svg"))

    print(f"\nVisualization files generated in {jsonl_file.parent}/")


if __name__ == "__main__":
    main()